Module1 task3 cli commands
htmlacademy-nodejs/1914019-typoteka-3 pull request #3
Opened 2021-12-28 11:38 UTC by Magistr19

2022-01-06 14:51 UTC, Krabaton requested changes

2022-01-06 14:51 UTC, Krabaton commented on src/service/cli/generate.js
> +    if (countOffer > 1000) {
1000 явно просится в константу по типу `DEFAULT_COUNT`

2022-01-06 14:51 UTC, Krabaton commented on src/service/cli/generate.js
> +    announce: shuffle(SENTENCES).slice(0, getRandomInt(1, 5)).join(` `),
А, что такое здесь 5? getRandomInt(1, 5) Почему именно 5? Может завести константу?

2022-01-10 07:57 UTC, Magistr19 commented on src/service/cli/generate.js
> +    if (countOffer > 1000) {
+

2022-01-10 07:57 UTC, Magistr19 commented on src/service/cli/generate.js
> +    announce: shuffle(SENTENCES).slice(0, getRandomInt(1, 5)).join(` `),
+

2022-01-11 16:43 UTC, merged