module2-task2 created .txt files for mocks
htmlacademy-nodejs/1914019-typoteka-3 pull request #5
Opened 2022-01-12 07:45 UTC by Magistr19

2022-01-13 01:28 UTC, Krabaton requested changes

2022-01-13 01:28 UTC, Krabaton commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Мало операций. Мы пропускаем пустые строки. Мы пропускаем пустые символы вокруг сообщений. Надо чистить каждую строку и убирать пустые строки.

2022-01-13 01:28 UTC, Krabaton commented on src/service/cli/generate.js
> +    const categories = await readContent(FILE_CATEGORIES_PATH);
На самом деле три await это не очень быстро, лучше их всех дождаться Promise.all
```js
const [sentences , titles , categories ] = await Promise.all([
   readContent(path.resolve(FILE_SENTENCES_PATH)),
   readContent(path.resolve(FILE_TITLES_PATH)),
   readContent(path.resolve(FILE_CATEGORIES_PATH))
])
```

2022-01-13 01:28 UTC, Krabaton commented on src/service/cli/generate.js
> +    const content = JSON.stringify(generateOffers(countOffer, titles, categories, sentences));
Многовато, аргументов, возможно  `titles, categories, sentences` лучше поместить в объект по типу `options`, Так точно ошибку не получим, что случайно местами поменяем аргумент

2022-01-15 18:50 UTC, Magistr19 commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
++ Пустые символы вокруг сообщений изначально trim уже делает в прошлом коммите?

2022-01-15 18:50 UTC, Magistr19 commented on src/service/cli/generate.js
> +    const categories = await readContent(FILE_CATEGORIES_PATH);
++

2022-01-15 18:50 UTC, Magistr19 commented on src/service/cli/generate.js
> +    const content = JSON.stringify(generateOffers(countOffer, titles, categories, sentences));
++

2022-01-16 15:42 UTC, Krabaton commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Нет) Этот `trim` уберет только пустые строки в начале и конце текста файла. У строк он оставить пустые символы. Т.е. строка типа `'     alala     '` Будет пропущена.

2022-01-16 15:42 UTC, merged